site_name: Collegium V Documentation
theme: flatly
pages:
  - Home: 'index.md'
  - Lounge:
    - Welcome: 'lounge/index.md'
    - Kitchen: 'lounge/kitchen.md'
    - TV and Media: 'lounge/media.md'
  - CVOS:
    - Start: 'cvos/index.md'
    - AUP: 'cvos/aup.md'
    - About: 'cvos/about.md'
    - Account Management: 'cvos/account-management.md'
    - User Preferences: 'cvos/user-preferences.md'
    - Browsers: 'cvos/browsers.md'
    - Office: 'cvos/office.md'
    - Print and Scan: 'cvos/print-and-scan.md'
    - Other Tools: 'cvos/tools.md'
    - Auxiliary Services: 'cvos/aux-services.md'
    - Bugs and Features: 'cvos/bugs-and-features.md'
  - Constellation:
    - What is it?: 'constellation/description.md'
    - OrderBoard: 'constellation/orderboard.md'
    - DeviceManager: 'constellation/device-manager.md'
  - Miscellaneous:
    - Social Media: 'misc/social-media.md'
markdown_extensions:
  - smarty
