site_name: Collegium V Documentation
theme: flatly
pages:
  - Home: 'index.md'
  - Lounge:
    - Welcome: 'lounge/index.md'
    - Getting Access: 'lounge/access.md'
    - Lounge Rules: 'lounge/policy.md'
    - Kitchen: 'lounge/kitchen.md'
  - CVOS:
    - Start: 'cvos/index.md'
    - About: 'cvos/about.md'
    - Accounts: 'cvos/account.md'
    - Browsers: 'cvos/browsers.md'
    - Office: 'cvos/office.md'
    - Print and Scan: 'cvos/print-and-scan.md'
    - Other Tools: 'cvos/tools.md'
    - Auxiliary Services: 'cvos/aux-services.md'
    - Bugs and Features: 'cvos/bugs-and-features.md'
  - Constellation:
    - What is it?: 'constellation/description.md'
    - OrderBoard: 'constellation/orderboard.md'
  - Miscellaneous:
    - TV and Media: 'misc/media.md'
    - Facebook Group: 'misc/facebook.md'
    - Twitter Feed: 'misc/twitter.md'
    - Mailing List: 'misc/listserve.md'
markdown_extensions:
  - smarty
